- id: golangci-lint
  name: golangci-lint
  description: Fast linters runner for Go. Note that only modified files are linted, so linters like 'unused' that need to scan all files won't work as expected.
  entry: golangci-lint run --new-from-rev HEAD --fix
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false
- id: golangci-lint-full
  name: golangci-lint-full
  description: Fast linters runner for Go. Runs on all files in the module. Use this hook if you use pre-commit in CI.
  entry: golangci-lint run --fix
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false
- id: golangci-lint-fmt
  name: golangci-lint-fmt
  description: Fast linters runner for Go. Formats all files in the repo.
  entry: golangci-lint fmt
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false
- id: golangci-lint-config-verify
  name: golangci-lint-config-verify
  description: Verifies the configuration file
  entry: golangci-lint config verify
  files: '\.golangci\.(?:yml|yaml|toml|json)'
  language: golang
  pass_filenames: false
