name: 🐞 Bug Report
description: "Create a report to help us improve."
labels: [bug]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Welcome
      options:
        - label: Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
          required: true
        - label: Yes, I've searched similar issues on GitHub and didn't find any.
          required: true
        - label: Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
          required: true
        - label: Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)
          required: true
        - label: I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Description of the problem
      placeholder: Your problem description
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version of golangci-lint
      value: |-
        <details>

        ```console
        $ golangci-lint --version
        # Paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      value: |-
        <details>

        ```console
        # paste configuration file or CLI flags here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: go-env
    attributes:
      label: Go environment
      value: |-
        <details>

        ```console
        $ go version && go env
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: verbose-output
    attributes:
      label: Verbose output of running
      value: |-
        <details>

        ```console
        $ golangci-lint cache clean
        $ golangci-lint run -v
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: A minimal reproducible example or link to a public repository
      description: if your problem is related to a private repository, a minimal reproducible example is required.
      value: |-
        <details>

        ```go
        // add your code here
        ```

        </details>
    validations:
      required: true

  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      options:
        - label: Yes, I've included all information above (version, config, etc.).
          required: true

  - type: checkboxes
    id: supporter
    attributes:
      label: Supporter
      options:
        - label: I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)
