//args: -Eexhaustive
//config_path: testdata/configs/exhaustive_generated.yml
package testdata

// Code generated by some program. DO NOT EDIT.

// Should not report missing cases in the switch statement below, because this
// is a generated file as indicated by the above comment
// (golang.org/s/generatedcode).

func processDirectionGenerated(d Direction) {
	switch d {
	case North, South:
	}
}
