name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:

  doc:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    env:
      # https://github.com/actions/setup-go#supported-version-syntax
      # ex:
      # - 1.18beta1 -> 1.18.0-beta.1
      # - 1.18rc1 -> 1.18.0-rc.1
      GO_VERSION: '1.24'
      HUGO_VERSION: 0.148.1
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: go mod download

      - name: Setup Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Build Documentation
        run: make docs_build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: docs/public
          force_orphan: true
          github_token: ${{ secrets.GOLANGCI_LINT_TOKEN }}
